<h1> RFM Aanlysis notebook

In [101]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.options.mode.chained_assignment = None  # default='warn'
pd.set_option('display.max_columns', None)

In [102]:
master_df = pd.read_csv('/Users/efkanturedi/Corteze/Python_output_folders/Ecommerce/for_RFM_DB.csv')

/Users/efkanturedi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (1,3,16,17,25) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [103]:
master_df

,order_id,payment_sequential,payment_type,payment_installments,payment_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,order_purchase_year,order_purchase_month,order_purchase_month_name,order_purchase_year_month,order_purchase_date,order_purchase_day,order_purchase_dayofweek,order_purchase_dayofweek_name,order_purchase_hour,order_purchase_time_day
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,0a8556ac6be836b46b3e89920d59291c,delivered,2018-04-25 22:01:49.000000000,2018-04-25 22:15:09.000000000,2018-05-02 15:20:00.000000000,2018-05-09 17:36:51.000000000,2018-05-22 00:00:00.000000000,1.0,af74cc53dcffc8384b29e7abfa41902b,213b25e6f54661939f11710a6fddb871,2018-05-02 22:15:09.000000000,79.8,19.53,4ce650e117a5b292bf5ea980a61eb61e,1,NÃ£o recomendo,"Produto com qualidade ruim, amassado e descasc...",2018-05-10 00:00:00,2018-05-15 23:38:00,708ab75d2a007f0564aedd11139c7708,39801,teofilo otoni,MG,Construction,57.0,921.0,8.0,800.0,17.0,27.0,17.0,13321.0,salto,SP,2018.0,4.0,Apr,201804.0,20180425.0,25.0,2.0,Wed,22.0,Night
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,f2c7fc58a9de810828715166c672f10a,delivered,2018-06-26 11:01:38.000000000,2018-06-26 11:18:58.000000000,2018-06-28 14:18:00.000000000,2018-06-29 20:32:09.000000000,2018-07-16 00:00:00.000000000,1.0,a630cc320a8c872f9de830cf121661a3,eaf6d55068dea77334e8477d3878d89e,2018-07-02 11:18:58.000000000,17.0,7.39,ad2036caca61484fc435d7e673c020f2,5,None,None,2018-06-30 00:00:00,2018-07-03 11:23:16,a8b9d3a27068454b1c98cc67d4e31e6f,2422,sao paulo,SP,Auto,59.0,1274.0,2.0,150.0,16.0,6.0,11.0,4660.0,sao paulo,SP,2018.0,6.0,Jun,201806.0,20180626.0,26.0,1.0,Tue,11.0,Morning
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,25b14b69de0b6e184ae6fe2755e478f9,delivered,2017-12-12 11:19:55.000000000,2017-12-14 09:52:34.000000000,2017-12-15 20:13:22.000000000,2017-12-18 17:24:41.000000000,2018-01-04 00:00:00.000000000,1.0,2028bf1b01cafb2d2b1901fca4083222,cc419e0650a3c5ba77189a1882b7556a,2017-12-26 09:52:34.000000000,56.99,8.72,bcddfa0f7d2e54cfc74bae4f01b84d92,5,None,Aprovada,2017-12-19 00:00:00,2017-12-22 17:55:30,6f70c0b2f7552832ba46eb57b1c5651e,2652,sao paulo,SP,Health_beauty,54.0,1536.0,2.0,250.0,20.0,8.0,21.0,9015.0,santo andre,SP,2017.0,12.0,Dec,201712.0,20171212.0,12.0,1.0,Tue,11.0,Morning
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,7a5d8efaaa1081f800628c30d2b0728f,delivered,2017-12-06 12:04:06.000000000,2017-12-06 12:13:20.000000000,2017-12-07 20:28:28.000000000,2017-12-21 01:35:51.000000000,2018-01-04 00:00:00.000000000,1.0,548e5bfe28edceab6b51fa707cc9556f,da8622b14eb17ae2831f4ac5b9dab84a,2017-12-12 12:13:20.000000000,89.9,17.88,c37a0e51e5df82bdb55d38ff0ffb6af3,5,None,None,2017-12-21 00:00:00,2017-12-21 21:42:31,87695ed086ebd36f20404c82d20fca87,36060,juiz de fora,MG,Home,60.0,188.0,1.0,1200.0,44.0,2.0,35.0,13405.0,piracicaba,SP,2017.0,12.0,Dec,201712.0,20171206.0,6.0,2.0,Wed,12.0,Morning
4,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,7a5d8efaaa1081f800628c30d2b0728f,delivered,2017-12-06 12:04:06.000000000,2017-12-06 12:13:20.000000000,2017-12-07 20:28:28.000000000,2017-12-21 01:35:51.000000000,2018-01-04 00:00:00.000000000,1.0,548e5bfe28edceab6b51fa707cc9556f,da8622b14eb17ae2831f4ac5b9dab84a,2017-12-12 12:13:20.000000000,89.9,17.88,5bc7680443b4ef765fec11a8201eeb0c,5,None,None,2017-12-21 00:00:00,2017-12-22 01:10:39,87695ed086ebd36f20404c82d20fca87,36060,juiz de fora,MG,Home,60.0,188.0,1.0,1200.0,44.0,2.0,35.0,13405.0,piracicaba,SP,2017.0,12.0,Dec,201712.0,20171206.0,6.0,2.0,Wed,12.0,Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118303,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31,5d576cb2dfa3bc05612c392a1ee9c654,delivered,2018-03-08 16:57:23.000000000,2018-03-10 03:55:25.000000000,2018-03-12 18:19:36.000000000,2018-03-16 13:09:51.000000000,2018-04-04 00:00:00.000000000,1.0,1302fd16bdfe85e523940c846370ef2c,a369d693961cb93b61ca2cc518872a85,2018-03-15 03:55:25.000000000,297.0,66.31,9f402e937d15b4664948410079ab687d,5,None,Tudo certo!,2018-03-17 00:00:00,2018-03-20 15:17:08,b6027ac07fb76ebca8c97b1887865aee,12954,atibaia,SP,Construction,31.0,309.0,1.0,13450.0,95.0,30.0,20.0,15081.0,sao jose do rio preto,SP,2018.0,3.0,Mar,201803.0,20180308.0,8.0,3.0,Thu,16.0,Afternoon
118304,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80,2079230c765a88530822a34a4cec2aa0,delivered,2017-08-18 09:45:35.000000000,2017-08-18 10:04:56.000000000,2017-08-18 18:04:24.000000000,2017-08-23 22:25:56.000000000,2017-09-12 00:00:00.000000000,1.0,fb55982be901439613a95940feefd9ee,3d871de0142ce09b7081e2b9d1733cb1,2017-08-24 10:04:56.000000000,79.0,17.8,f78d2909c6c202d3cabb8bac3fc00e75,5,None,None,2017-08-24 00:00:00,2017-08-25 19:38:31,53b30ca78efb2b7efcd3f9e461587eb2,30210,belo horizonte,MG,Office,52.0,211.0,2.0,7000.0,60.0,20.0,30.0,13232.0,campo limpo paulista,SP,2017.0,8.0,Aug,201708.0,20170818.0,18.0,4.0,Fri,9.0,Morning
118305,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77,e4abb5057ec8cfda9759c0dc415a8188,invoiced,2017-11-18 17:27:14.000000000,2017-11-18 17:46:05.000000000,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000000,2017-12-05 00:00:00.000000000,1.0,848ef0a103ee21407d1fbd0f7e7ae179,3d621842b2ed28e2b474132480edac3c,2017-11-27 17:46:05.000000000,39.99,7.78,2cdb88f8dce688bb85e20a5cf069e589,1,None,None,2017-12-07 00:00:00,2017-12-07 09:00:59,d3c7da954a324253814096bcaf240e4e,1519,sao paulo,SP,Auto,47.0,577.0,2.0,120.0,16.0,8.0,11.0,8041.0,sao paulo,SP,2017.0,11.0,Nov,201711.0,20171118.0,18.0,5.0,Sat,17.0,Afternoon
118306,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54,5d719b0d300663188169c6560e243f27,delivered,2018-08-07 23:26:13.000000000,2018-08-07 23:45:00.000000000,2018-08-09 11:46:00.000000000,2018-08-21 22:41:46.000000000,2018-08-24 00:00:00.000000000,1.0,e9c1abcc7126360336d8f56d49041a8c,679769a98cfcc6da877c8486ff1c13f3,2018-08-13 23:45:00.000000000,349.0,20.54,6c698e5d193ab18db7615ea75a28866e,5,None,None,2018-08-22 00:00:00,2018-08-23 15:29:34,b84dc68f02f122a88d7e7bbd37b06204,22733,rio de janeiro,RJ,Health_beauty,42.0,3902.0,7.0,500.0,22.0,6.0,16.0,35162.0,ipatinga,MG,2018.0,8.0,Aug,201808.0,20180807.0,7.0,1.0,Tue,23.0,Night
118307,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58,4c7f868f43b5cff577b0becb8c8b7860,delivered,2017-12-05 08:18:35.000000000,2017-12-06 02:50:09.000000000,2017-12-08 00:51:47.000000000,2018-02-05 14:59:09.000000000,2017-12-29 00:00:00.000000000,1.0,1cdfaf0cc5abd6063d3a10ae3318f345,da8622b14eb17ae2831f4ac5b9dab84a,2017-12-12 02:50:09.000000000,169.9,21.68,fa9bd3a24482e2dfd0c776446baec09f,1,None,Ja passou do prazo e eu ainda nao recebi o pro...,2018-01-04 00:00:00,2018-01-04 10:00:40,b1f51a4e19da3338e51fbcfabefad1bf,23059,rio de janeiro,RJ,Home,60.0,298.0,1.0,2350.0,33.0,7.0,39.0,13405.0,piracicaba,SP,2017.0,12.0,Dec,201712.0,20171205.0,5.0,1.0,Tue,8.0,Morning

In [104]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118308 entries, 0 to 118307
Data columns (total 49 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118305 non-null  object
 1   payment_sequential             118308 non-null  object
 2   payment_type                   118308 non-null  object
 3   payment_installments           118308 non-null  object
 4   payment_value                  118308 non-null  float64
 5   customer_id                    118308 non-null  object
 6   order_status                   118308 non-null  object
 7   order_purchase_timestamp       118308 non-null  object
 8   order_approved_at              118308 non-null  object
 9   order_delivered_carrier_date   118308 non-null  object
 10  order_delivered_customer_date  118308 non-null  object
 11  order_estimated_delivery_date  118308 non-null  object
 12  order_item_id                  118308 non-null  float64
 13  product_id                     118308 non-null  object
 14  seller_id                      118308 non-null  object
 15  shipping_limit_date            118308 non-null  object
 16  price                          118308 non-null  object
 17  freight_value                  118308 non-null  object
 18  review_id                      118308 non-null  object
 19  review_score                   118308 non-null  int64
 20  review_comment_title           118308 non-null  object
 21  review_comment_message         118308 non-null  object
 22  review_creation_date           118305 non-null  object
 23  review_answer_timestamp        118305 non-null  object
 24  customer_unique_id             118305 non-null  object
 25  customer_zip_code_prefix       118305 non-null  object
 26  customer_city                  118305 non-null  object
 27  customer_state                 118305 non-null  object
 28  product_category_name          118302 non-null  object
 29  product_name_lenght            118302 non-null  float64
 30  product_description_lenght     118302 non-null  float64
 31  product_photos_qty             118302 non-null  float64
 32  product_weight_g               118302 non-null  float64
 33  product_length_cm              118302 non-null  float64
 34  product_height_cm              118302 non-null  float64
 35  product_width_cm               118302 non-null  float64
 36  seller_zip_code_prefix         118302 non-null  float64
 37  seller_city                    118302 non-null  object
 38  seller_state                   118302 non-null  object
 39  order_purchase_year            118302 non-null  float64
 40  order_purchase_month           118302 non-null  float64
 41  order_purchase_month_name      118302 non-null  object
 42  order_purchase_year_month      118302 non-null  float64
 43  order_purchase_date            118302 non-null  float64
 44  order_purchase_day             118302 non-null  float64
 45  order_purchase_dayofweek       118302 non-null  float64
 46  order_purchase_dayofweek_name  118302 non-null  object
 47  order_purchase_hour            118302 non-null  float64
 48  order_purchase_time_day        118302 non-null  object
dtypes: float64(17), int64(1), object(31)
memory usage: 44.2+ MB

In [105]:
df = master_df[[
    'customer_unique_id',
    'order_id',
    'order_status',
    'order_purchase_date',
    'product_id',
    'order_item_id',
    'price',
    'product_category_name'
    ]].copy()

In [106]:
df['order_purchase_date'] = pd.to_datetime(df['order_purchase_date'], format='%Y%m%d')

In [107]:
# Setting reference day
df['today'] = df['order_purchase_date'].max()
# Date deltas
df['recency'] = df['today'] - df['order_purchase_date']

In [108]:
df = df[df['order_status']=='delivered']
df.reset_index(drop=True,inplace=True)

In [109]:
df['price'] = pd.to_numeric(df['price'])

In [110]:
df['price'].dtype

dtype('float64')

In [111]:
df['total_price'] = df['order_item_id'] * df['price']

In [112]:
df

,customer_unique_id,order_id,order_status,order_purchase_date,product_id,order_item_id,price,product_category_name,today,recency,total_price
0,708ab75d2a007f0564aedd11139c7708,b81ef226f3fe1789b1e8b2acac839d17,delivered,2018-04-25,af74cc53dcffc8384b29e7abfa41902b,1.0,79.80,Construction,2018-09-03,131 days,79.80
1,a8b9d3a27068454b1c98cc67d4e31e6f,a9810da82917af2d9aefd1278f1dcfa0,delivered,2018-06-26,a630cc320a8c872f9de830cf121661a3,1.0,17.00,Auto,2018-09-03,69 days,17.00
2,6f70c0b2f7552832ba46eb57b1c5651e,25e8ea4e93396b6fa0d3dd708e76c1bd,delivered,2017-12-12,2028bf1b01cafb2d2b1901fca4083222,1.0,56.99,Health_beauty,2018-09-03,265 days,56.99
3,87695ed086ebd36f20404c82d20fca87,ba78997921bbcdc1373bb41e913ab953,delivered,2017-12-06,548e5bfe28edceab6b51fa707cc9556f,1.0,89.90,Home,2018-09-03,271 days,89.90
4,87695ed086ebd36f20404c82d20fca87,ba78997921bbcdc1373bb41e913ab953,delivered,2017-12-06,548e5bfe28edceab6b51fa707cc9556f,1.0,89.90,Home,2018-09-03,271 days,89.90
...,...,...,...,...,...,...,...,...,...,...,...
115714,13f283df2f4760f22b57830865761d07,c45067032fd84f4cf408730ff5205568,delivered,2018-05-16,fea2f92877b647dc07ea8e3f4aa2cf3f,1.0,179.80,Arts,2018-09-03,110 days,179.80
115715,b6027ac07fb76ebca8c97b1887865aee,0406037ad97740d563a178ecc7a2075c,delivered,2018-03-08,1302fd16bdfe85e523940c846370ef2c,1.0,297.00,Construction,2018-09-03,179 days,297.00
115716,53b30ca78efb2b7efcd3f9e461587eb2,7b905861d7c825891d6347454ea7863f,delivered,2017-08-18,fb55982be901439613a95940feefd9ee,1.0,79.00,Office,2018-09-03,381 days,79.00
115717,b84dc68f02f122a88d7e7bbd37b06204,b8b61059626efa996a60be9bb9320e10,delivered,2018-08-07,e9c1abcc7126360336d8f56d49041a8c,1.0,349.00,Health_beauty,2018-09-03,27 days,349.00
115718,b1f51a4e19da3338e51fbcfabefad1bf,28bbae6599b09d39ca406b747b6632b1,delivered,2017-12-05,1cdfaf0cc5abd6063d3a10ae3318f345,1.0,169.90,Home,2018-09-03,272 days,169.90

In [113]:
df[df['customer_unique_id']=='31e412b9fb766b6794724ed17a41dfa6']

,customer_unique_id,order_id,order_status,order_purchase_date,product_id,order_item_id,price,product_category_name,today,recency,total_price
110427,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,1.0,59.0,Garden_pets,2018-09-03,264 days,59.0
110428,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,2.0,59.0,Garden_pets,2018-09-03,264 days,118.0
110429,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,3.0,59.0,Garden_pets,2018-09-03,264 days,177.0
110430,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,4.0,59.0,Garden_pets,2018-09-03,264 days,236.0
110431,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,5.0,59.0,Garden_pets,2018-09-03,264 days,295.0
110432,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,6.0,59.0,Garden_pets,2018-09-03,264 days,354.0
110433,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,7.0,59.0,Garden_pets,2018-09-03,264 days,413.0
110434,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,8.0,59.0,Garden_pets,2018-09-03,264 days,472.0
110435,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,9.0,59.0,Garden_pets,2018-09-03,264 days,531.0
110436,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,10.0,59.0,Garden_pets,2018-09-03,264 days,590.0
110437,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,11.0,59.0,Garden_pets,2018-09-03,264 days,649.0
110438,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,12.0,59.0,Garden_pets,2018-09-03,264 days,708.0
110439,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,13.0,59.0,Garden_pets,2018-09-03,264 days,767.0
110440,31e412b9fb766b6794724ed17a41dfa6,73c8ab38f07dc94389065f7eba4f297a,delivered,2017-12-13,422879e10f46682990de24d770e7f83d,14.0,59.0,Garden_pets,2018-09-03,264 days,826.0

In [114]:
# Grouping by customer and order (same order_id = same day); This will be the data frame which contains all valid costomers and how they are segmented
df_segmented = df.groupby([
    'customer_unique_id',
    'order_id'
    ], as_index=False).agg({
        'order_purchase_date': 'first',
        'order_item_id': 'max',
        'total_price': 'sum',
        'today': 'first',
        'recency': 'first'
        })

In [115]:
df_segmented

,customer_unique_id,order_id,order_purchase_date,order_item_id,total_price,today,recency
0,0000366f3b9a7992bf8c76cfdf3221e2,e22acc9c116caa3f2b7121bbb380d08e,2018-05-10,1.0,129.90,2018-09-03,116 days
1,0000b849f77a49e4a4ce2b2a4ca5be3f,3594e05a005ac4d06a72673270ef9ec9,2018-05-07,1.0,18.90,2018-09-03,119 days
2,0000f46a3911fa3c0805444483337064,b33ec3b699337181488304f362a6b734,2017-03-10,1.0,69.00,2018-09-03,542 days
3,0000f6ccb0745a6a4b88665a16c9f078,41272756ecddd9a9ed0180413cc22fb6,2017-10-12,1.0,25.99,2018-09-03,326 days
4,0004aac84e0df4da2b147fca70cf8255,d957021f1127559cd947b62533f484f7,2017-11-14,1.0,180.00,2018-09-03,293 days
...,...,...,...,...,...,...,...
96464,fffcf5a5ff07b0908bd4e2dbc735a684,725cf8e9c24e679a8a5a32cb92c9ce1e,2017-06-08,2.0,2250.00,2018-09-03,452 days
96465,fffea47cd6d3cc0a88bd621562a9d061,c71b9252fd7b3b263aaa4cb09319a323,2017-12-10,1.0,64.89,2018-09-03,267 days
96466,ffff371b4d645b6ecea244b27531430a,fdc45e6c7555e6cb3cc0daca2557dbe1,2017-02-07,1.0,89.90,2018-09-03,573 days
96467,ffff5962728ec6157033ef9805bacc48,94d3ee0bc2a0af9d4fa47a4d63616e8d,2018-05-02,1.0,115.00,2018-09-03,124 days
96468,ffffd2657e2aad2907e67c3e9daecbeb,f79a35da168301ae56922475da21117b,2017-05-02,1.0,56.99,2018-09-03,489 days

In [119]:
df_segmented['average_price'] = df_segmented['total_price'] / df_segmented['order_item_id']

In [120]:
df_segmented['recency'] = df_segmented['recency'].astype(str)
df_segmented['recency'] = df_segmented['recency'].str.replace(r'\s+days.*', '', regex=True)
df_segmented['recency'] = df_segmented['recency'].astype(int)

In [121]:
df_segmented

,customer_unique_id,order_id,order_purchase_date,order_item_id,total_price,today,recency,average_price
0,0000366f3b9a7992bf8c76cfdf3221e2,e22acc9c116caa3f2b7121bbb380d08e,2018-05-10,1.0,129.90,2018-09-03,116,129.90
1,0000b849f77a49e4a4ce2b2a4ca5be3f,3594e05a005ac4d06a72673270ef9ec9,2018-05-07,1.0,18.90,2018-09-03,119,18.90
2,0000f46a3911fa3c0805444483337064,b33ec3b699337181488304f362a6b734,2017-03-10,1.0,69.00,2018-09-03,542,69.00
3,0000f6ccb0745a6a4b88665a16c9f078,41272756ecddd9a9ed0180413cc22fb6,2017-10-12,1.0,25.99,2018-09-03,326,25.99
4,0004aac84e0df4da2b147fca70cf8255,d957021f1127559cd947b62533f484f7,2017-11-14,1.0,180.00,2018-09-03,293,180.00
...,...,...,...,...,...,...,...,...
96464,fffcf5a5ff07b0908bd4e2dbc735a684,725cf8e9c24e679a8a5a32cb92c9ce1e,2017-06-08,2.0,2250.00,2018-09-03,452,1125.00
96465,fffea47cd6d3cc0a88bd621562a9d061,c71b9252fd7b3b263aaa4cb09319a323,2017-12-10,1.0,64.89,2018-09-03,267,64.89
96466,ffff371b4d645b6ecea244b27531430a,fdc45e6c7555e6cb3cc0daca2557dbe1,2017-02-07,1.0,89.90,2018-09-03,573,89.90
96467,ffff5962728ec6157033ef9805bacc48,94d3ee0bc2a0af9d4fa47a4d63616e8d,2018-05-02,1.0,115.00,2018-09-03,124,115.00
96468,ffffd2657e2aad2907e67c3e9daecbeb,f79a35da168301ae56922475da21117b,2017-05-02,1.0,56.99,2018-09-03,489,56.99

In [ ]:
filepath = '/Users/efkanturedi/Corteze/Python_output_folders/Ecommerce/'
df_segmented.to_csv(filepath+'final_for_ML.csv',index=False)